# Generated by Django 5.1.1 on 2024-09-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_is_superuser_customeuser_is_superadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeuser',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
    ]
