# Generated by Django 5.1.1 on 2024-09-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_is_superadmin_customeuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeuser',
            options={'verbose_name': 'User'},
        ),
    ]
