# Generated by Django 5.1.1 on 2024-10-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/avatars/profile_avatar', null=True, upload_to='phtoes/user_profile/'),
        ),
    ]
