# Generated by Django 5.1.1 on 2024-10-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewraiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewraiting',
            old_name='raiting',
            new_name='rating',
        ),
    ]
