# Generated by Django 5.1.1 on 2024-10-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_raiting_reviewraiting_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewraiting',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
