# Generated by Django 5.1 on 2024-09-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_color_size_variation_delete_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="variation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.variation",
            ),
        ),
    ]
