# Generated by Django 5.1 on 2024-09-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="variation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.variation",
            ),
        ),
    ]
