# Generated by Django 5.1.1 on 2024-10-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(height_field=100, upload_to='phtoes/gallery', width_field=100),
        ),
    ]
