# Generated by Django 5.1 on 2024-09-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="colors",
            field=models.ManyToManyField(blank=True, to="store.color"),
        ),
        migrations.AlterField(
            model_name="variation",
            name="sizes",
            field=models.ManyToManyField(blank=True, to="store.size"),
        ),
    ]
