# Generated by Django 5.1 on 2024-09-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem_json_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="json_variation",
        ),
    ]
