# Generated by Django 5.1 on 2024-09-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_remove_cartitem_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="json_variation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
