# Generated by Django 5.1 on 2024-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_remove_cartitem_json_variation_cartitem_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="variation",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="json_variation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
